[package]
name = "speedy"
version = "0.8.7"
authors = ["Jan Bujak <j@exia.io>"]
edition = "2018"
description = "A fast binary serialization framework"
documentation = "https://docs.rs/speedy/*/speedy/"
readme = "README.md"
homepage = "https://github.com/koute/speedy"
repository = "https://github.com/koute/speedy"
license = "MIT/Apache-2.0"
keywords = ["serialization"]
categories = ["encoding"]

[package.metadata.docs.rs]
features = ["external_doc"]

[workspace]
members = [".", "speedy-derive", "static-tests"]

[dependencies]
chrono = { version = "0.4", optional = true }
glam = { version = ">= 0.15, <= 0.29", optional = true }
indexmap_v1 = { version = "1", optional = true, package = "indexmap" }
indexmap_v2 = { version = "2", optional = true, package = "indexmap" }
memoffset = "0.9"
regex = { version = "1", default-features = false, optional = true }
rust_decimal = { version = "1.37.2", optional = true }
smallvec = { version = "1", optional = true }
speedy-derive = { version = "= 0.8.7", optional = true, path = "speedy-derive" }
uuid = { version = "1", default-features = false, optional = true }

[dev-dependencies]
paste = "1"
quickcheck = "1"
tempfile = "3"

[features]
alloc = []
default = ["rust_decimal", "speedy-derive", "std"]
external_doc = []
indexmap = ["indexmap_v1"]
indexmap_v1 = ["dep:indexmap_v1"]
indexmap_v2 = ["dep:indexmap_v2"]
std = ["alloc"]

[profile.release]
panic = "abort"
